version: '1'

services:
  rust-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: rust_server
    container_name: rust_server
    tty: true
    command: ./target/release/elastic
    ports:
      - "1234:1234"

networks:
  app-network:
    driver: bridge
